REM INSERTING into APP_CONTACT_ROLES
SET DEFINE OFF;
Insert into APP_CONTACT_ROLES (ID,DISPLAY_SEQ,CODE,MEANING,DESCRIPTION,ACTIVE_IND) values (1,1,'BOSS','Boss',null,'Y');
Insert into APP_CONTACT_ROLES (ID,DISPLAY_SEQ,CODE,MEANING,DESCRIPTION,ACTIVE_IND) values (2,10,'ACCOUNTS','Accounts',null,'Y');
Insert into APP_CONTACT_ROLES (ID,DISPLAY_SEQ,CODE,MEANING,DESCRIPTION,ACTIVE_IND) values (3,20,'CLAIMS','Claims',null,'Y');
Insert into APP_CONTACT_ROLES (ID,DISPLAY_SEQ,CODE,MEANING,DESCRIPTION,ACTIVE_IND) values (4,30,'MAIN','Main',null,'Y');

