REM INSERTING into APP_CLIENT_CONTACTS
SET DEFINE OFF;
Insert into APP_CLIENT_CONTACTS (ID,PARTY_ID,CLIENT_ID,CONTACT_ROLE_CODE,ACTIVE_IND) values (21,21,2,'ACCOUNTS','Y');
Insert into APP_CLIENT_CONTACTS (ID,PARTY_ID,CLIENT_ID,CONTACT_ROLE_CODE,ACTIVE_IND) values (1,1,2,'BOSS','Y');
Insert into APP_CLIENT_CONTACTS (ID,PARTY_ID,CLIENT_ID,CONTACT_ROLE_CODE,ACTIVE_IND) values (41,41,2,'ACCOUNTS','Y');

