REM INSERTING into APP_PARTY
SET DEFINE OFF;
Insert into APP_PARTY (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,COMPANY_NAME,EMAIL1_TYPE,EMAIL1,EMAIL2_TYPE,EMAIL2,EMAIL3_TYPE,EMAIL3,PHONE1_TYPE,PHONE1,PHONE2_TYPE,PHONE2,PHONE3_TYPE,PHONE3) values (41,'James','D.','Halpert','Dunder','PERSONAL','TheMan@company.com',null,null,null,null,'MAIN','555 1212','DIRECT',null,null,null);
Insert into APP_PARTY (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,COMPANY_NAME,EMAIL1_TYPE,EMAIL1,EMAIL2_TYPE,EMAIL2,EMAIL3_TYPE,EMAIL3,PHONE1_TYPE,PHONE1,PHONE2_TYPE,PHONE2,PHONE3_TYPE,PHONE3) values (21,'Dwight',null,'Schrute','Dunder','PERSONAL','TheSilentNinja@SchruteFarms.com','MAIN','dschrute@dm.us',null,null,'MAIN','800 555-1212',null,null,null,null);
Insert into APP_PARTY (ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,COMPANY_NAME,EMAIL1_TYPE,EMAIL1,EMAIL2_TYPE,EMAIL2,EMAIL3_TYPE,EMAIL3,PHONE1_TYPE,PHONE1,PHONE2_TYPE,PHONE2,PHONE3_TYPE,PHONE3) values (1,'Michael',null,'Scott','Dunder','DIRECT','michael.scott@dm.us','PERSONAL','mike@gmail.com',null,null,'DIRECT','800 555-1212','PERSONAL','952 555-1212','FAX','1234567');

