create table books (
  id number not null enable, 
  book_name varchar2(100) not null enable, 
  author varchar2(100), 
  year number, 
  summary varchar2(1000)
)
/
REM INSERTING into BOOKS
SET DEFINE OFF;
insert into BOOKS (ID,BOOK_NAME,AUTHOR,YEAR,SUMMARY) values (1,'Relic','Preston/Child',1995,'In and around a fictionalized version of New York City''s American Museum of Natural History, a few select characters must solve a string of brutal murders that take place inside the museum during the days preceding the opening of "Superstition", a spectacular blockbuster exhibition.');
insert into BOOKS (ID,BOOK_NAME,AUTHOR,YEAR,SUMMARY) values (2,'Reliquary','Preston/Child',1997,'The story picks up where the epilogue of Relic left off. Two headless skeletons are found in the Humboldt Kill. When further decapitated bodies follow, there is suspicion of a second Mbwun monster. Major characters from the original book team up with new ones to solve the puzzle. The mystery soon leads underground to the Mole people, and even deeper towards enigmatic beings called the Wrinklers. In the end, it is revealed that the Wrinklers are led by Frock, who has refined a modified version of the Mbwun plant, created by Kawakita to regain the use of his legs. Kawakita also gave the drug to the people who were to become the Wrinklers, later made into his tribe by Frock. After going underground, the group kills them with an explosion, vitamin D infused water and a flood.');
insert into BOOKS (ID,BOOK_NAME,AUTHOR,YEAR,SUMMARY) values (3,'The Cabinet of Curiosities','Preston/Child',2002,'Dr. Nora Kelly''s life as an archeologist at New York City''s American Museum of Natural History becomes complicated when Aloysius X. L. Pendergast, a secretive and highly resourceful FBI Special Agent, convinces her to help him uncover the truth behind a string of brutal murders that appears to stretch back 130 years.');
insert into BOOKS (ID,BOOK_NAME,AUTHOR,YEAR,SUMMARY) values (4,'Still Life with Crows','Preston/Child',2003,'Agent Pendergast visits Medicine Creek, Kansas after a gruesome murder occurs. With the help of local teenaged misfit Corrie Swanson, he continues to investigate as more citizens are killed. Pendergast is soon led to believe that the murderer must be a member of the community. He soon discovers that the murders are connected to an old curse.');
insert into BOOKS (ID,BOOK_NAME,AUTHOR,YEAR,SUMMARY) values (5,'Brimstone','Preston/Child',2004,'FBI Special Agent Aloysius X.L. Pendergast and Sergeant Vincent D''Agosta, now working for the Southampton Police Department, investigate a series of unusual deaths—deaths that appear to be the work of Lucifer in return for pacts entered in with him by his victims. Their investigation takes them from the New York City area, site of the first two deaths, to Florence, Italy where they uncover the motive and method of the killers behind the strange and gruesome deaths. During the course of unraveling the mystery, the truth behind a priceless, missing Stradivarius violin is revealed and a potentially apocalyptic riot with Messianic Christians is averted. Pendergast also reveals details of his insane brother Diogenes, whom he believes is planning something horrible.');
insert into BOOKS (ID,BOOK_NAME,AUTHOR,YEAR,SUMMARY) values (6,'Dance of Death','Preston/Child',2005,'The book follows FBI Special Agent Aloysius Pendergast and his sidekick, Lieutenant Vincent D''Agosta. Pendergast was last seen at the end of the first novel, Brimstone, where he was buried alive behind a brick wall in Castel Fosco. His estranged brother, Diogenes, rescues him and nurses him back to health. However this is not a true act of kindness; Diogenes has a dark agenda and needs his brother alive in order to carry out his nefarious plans.');
insert into BOOKS (ID,BOOK_NAME,AUTHOR,YEAR,SUMMARY) values (7,'The Book of the Dead','Preston/Child',2006,'Special Agent Aloysius Pendergast is the focus of this novel as his evil brother Diogenes puts several plans into effect. One plan involves targeting Aloysius''s dearest friends...and casual acquaintances.');
